"""exercise subtitle column

Revision ID: 1844f5451b34
Revises: e161f38756ee
Create Date: 2021-02-28 08:59:05.610299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1844f5451b34'
down_revision = 'e161f38756ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('subtitle', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'subtitle')
    # ### end Alembic commands ###
